apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi
spec:
  template:
    spec:
      containers:
        - name: reader
          volumeMounts:
            - mountPath: /mnt/files-in
              name: files
        - name: writer
          volumeMounts:
            - mountPath: /mnt/files-out
              name: files