apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: web-client
  name: web-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-client
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: web-client
    spec:
      containers:
      - command:
        - sleep
        - "300"
        image: alpine
        name: alpine
        resources: {}
status: {}
