apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/deployment.yaml
  - ../../base/service-clusterip.yaml

nameSuffix: -cip

commonLabels:
  variant: with-clusterip-service