apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: multi
  name: multi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multi
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: multi
    spec:
      containers:
      - command:
        - /usr/local/bin/bash
        - -c
        - |2

          while true;
          do
            echo I read
            sleep 1
          done
        image: bash
        name: reader
        resources: {}
status: {}
