apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: multi
  name: multi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multi
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: multi
    spec:
      containers:
      - command:
        - /usr/local/bin/bash
        - -c
        - |-
          IFS=$'\n\t'
          set -euxo pipefail

          COUNTER=0

          while true;
          do
            touch /mnt/files-out/file-$COUNTER.txt
            sleep .1
            (( COUNTER++ )) || true
          done
        image: bash
        name: writer
        resources: {}
status: {}
