apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: web-server-clusterip
  name: web-server-clusterip
spec:
  ports:
  - name: 7071-80
    port: 7071
    protocol: TCP
    targetPort: 80
  selector:
    app: web-server-clusterip
  type: ClusterIP
status:
  loadBalancer: {}
