apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: web-server-loadbalancer
  name: web-server-loadbalancer
spec:
  ports:
  - name: 7072-80
    port: 7072
    protocol: TCP
    targetPort: 80
  selector:
    app: web-server-loadbalancer
  type: LoadBalancer
status:
  loadBalancer: {}
