apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: postgres-on-k8s
  name: postgres-on-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-on-k8s
  strategy: {}
  template:
    metadata:
      labels:
        app: postgres-on-k8s
    spec:
      containers:
      - env:
        - name: POSTGRES_PASSWORD
          value: minikube
        image: postgres:latest
        name: postgres
        ports:
        - containerPort: 5432
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-data
      volumes:
      - emptyDir: {}
        name: postgres-data
status: {}
