apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: postgres-on-k8s-cronjob-copy-to-nginx
spec:
  jobTemplate:
    metadata:
      name: postgres-on-k8s-cronjob-copy-to-nginx
    spec:
      template:
        spec:
          containers:
            - name: postgres-on-k8s-cronjob-copy-to-nginx
              env:
                - name: DB_SERVICE_URL
                  value: postgres-on-k8s-dd
                - name: DB_SERVICE_PORT
                  value: "5432"
                - name: PASSWORD
                  value: minikube
              volumeMounts:
                - mountPath: /usr/share/nginx/html
                  name: html-files
          volumes:
            - name: html-files
              persistentVolumeClaim:
                claimName: shared-data-persistent-volume-claim