apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-on-k8s
spec:
  template:
    spec:
      containers:
        - name: postgres
          env:
            - name: POSTGRES_PASSWORD
              value: postgres