apiVersion: batch/v1
kind: Job
metadata:
  name: postgres-on-k8s-job-to-tear-down-db
spec:
  template:
    spec:
      containers:
        - name: postgres-on-k8s-job-to-tear-down-db
          env:
          - name: DB_SERVICE_URL
            value: postgres-on-k8s-dd
          - name: DB_SERVICE_PORT
            value: "5432"