apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: rest-client
  name: rest-client
spec:
  ports:
  - port: 7071
    protocol: TCP
    targetPort: 8081
  selector:
    app: rest-client
  type: NodePort
status:
  loadBalancer: {}
