apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: rest-client
  name: rest-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest-client
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rest-client
    spec:
      containers:
      - image: marekdudek/rest-client
        name: rest-client
        ports:
        - containerPort: 8081
        resources: {}
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8081
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8081
        lifecycle:
          preStop:
            exec:
              command: ["sh", "-c", "sleep 10"]
        volumeMounts:
          - name: config-volume
            mountPath: /workspace/config
      volumes:
        - name: config-volume
          configMap:
            name: rest-client-config
status: {}
