apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/deployment.yaml


images:
  - name: alpine
    newTag: 3.11.7

commonAnnotations:
  creator: Marek Dudek

commonLabels:
  variant: with-clusterip-client
  owner: mdudek

nameSuffix: -cip

patchesStrategicMerge:
  - env-variables-patch.yaml