apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/deployment.yaml

nameSuffix: -cip

commonLabels:
  variant: with-clusterip-client

patchesStrategicMerge:
  - env-variables-patch.yaml