apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: dpl-1
  name: svc-1
  namespace: ns-1
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: dpl-1
  type: NodePort
status:
  loadBalancer: {}
