apiVersion: v1
kind: Service
metadata:
  annotations:
    creator: Marek Dudek
  creationTimestamp: null
  labels:
    app: web-server
    owner: mdudek
    variant: production
  name: web-server
  namespace: prod
spec:
  ports:
  - name: 7072-80
    port: 7072
    protocol: TCP
    targetPort: 80
  selector:
    app: web-server
    owner: mdudek
    variant: production
  type: NodePort
status:
  loadBalancer: {}
