apiVersion: v1
kind: Service
metadata:
  annotations:
    creator: Marek Dudek
  creationTimestamp: null
  labels:
    app: web-server-loadbalancer
    owner: mdudek
    variant: production
  name: web-server-loadbalancer
  namespace: prod
spec:
  ports:
  - name: 7072-80
    port: 7072
    protocol: TCP
    targetPort: 80
  selector:
    app: web-server-loadbalancer
    owner: mdudek
    variant: production
  type: LoadBalancer
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    creator: Marek Dudek
  creationTimestamp: null
  labels:
    app: web-server
    owner: mdudek
    variant: production
  name: web-server
  namespace: prod
spec:
  ports:
  - name: 7072-80
    port: 7072
    protocol: TCP
    targetPort: 80
  selector:
    app: web-server
    owner: mdudek
    variant: production
  type: NodePort
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    creator: Marek Dudek
  creationTimestamp: null
  labels:
    app: web-server
    owner: mdudek
    variant: production
  name: web-server
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-server
      owner: mdudek
      variant: production
  strategy: {}
  template:
    metadata:
      annotations:
        creator: Marek Dudek
      creationTimestamp: null
      labels:
        app: web-server
        owner: mdudek
        variant: production
    spec:
      containers:
      - image: nginx:1.18.0
        name: nginx
        ports:
        - containerPort: 80
        resources: {}
status: {}
