apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    creator: Marek Dudek
  creationTimestamp: null
  labels:
    app: web-server
    owner: mdudek
    variant: production
  name: web-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-server
      owner: mdudek
      variant: production
  strategy: {}
  template:
    metadata:
      annotations:
        creator: Marek Dudek
      creationTimestamp: null
      labels:
        app: web-server
        owner: mdudek
        variant: production
    spec:
      containers:
      - image: nginx:1.18.0
        name: nginx
        ports:
        - containerPort: 80
        resources: {}
status: {}
