apiVersion: v1
kind: Service
metadata:
  annotations:
    creator: Marek Dudek
  creationTimestamp: null
  labels:
    app: web-server-loadbalancer
    owner: mdudek
    variant: production
  name: web-server-loadbalancer
  namespace: prod
spec:
  ports:
  - name: 7073-80
    port: 7073
    protocol: TCP
    targetPort: 80
  selector:
    app: web-server-loadbalancer
    owner: mdudek
    variant: production
  type: LoadBalancer
status:
  loadBalancer: {}
