apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: postgres-on-k8s-job-to-tear-down-db
spec:
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - command:
        - /bin/bash
        - -c
        - |-
          PGPASSWORD="$PASSWORD" dropdb   --echo -U postgres -h "${DB_SERVICE_URL}" -p "${DB_SERVICE_PORT}" my_db
          PGPASSWORD="$PASSWORD" dropuser --echo -U postgres -h "${DB_SERVICE_URL}" -p "${DB_SERVICE_PORT}" db_user
        image: postgres:latest
        name: postgres-on-k8s-job-to-tear-down-db
        resources: {}
      restartPolicy: Never
status: {}
