apiVersion: batch/v1beta1
kind: CronJob
metadata:
  creationTimestamp: null
  name: postgres-on-k8s-cronjob-copy-to-nginx
spec:
  jobTemplate:
    metadata:
      creationTimestamp: null
      name: postgres-on-k8s-cronjob-copy-to-nginx
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - command:
            - /bin/bash
            - -c
            - |-
              IFS=$'\n\t'
              set -euxo pipefail

              PGPASSWORD="$CLIENT_PASSWORD" psql \
                --user="$CLIENT_USER" \
                --host="$DB_SERVICE_URL" \
                --port="$DB_SERVICE_PORT" \
                --dbname=my_db \
                --output=index.html \
                --html \
                --command="
                  SELECT * FROM some_table
                "

              cp index.html /usr/share/nginx/html
            image: postgres:latest
            name: postgres-on-k8s-cronjob-copy-to-nginx
            resources: {}
          restartPolicy: OnFailure
  schedule: '* * * * *'
status: {}
