apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: postgres-on-k8s-job-to-set-up-db
spec:
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - |-
          PGPASSWORD=postgres createuser --echo -U postgres -h "${DB_SERVICE_URL}" -p "${DB_SERVICE_PORT}" db_user
          PGPASSWORD=postgres psql              -U postgres -h "${DB_SERVICE_URL}" -p "${DB_SERVICE_PORT}" -c "ALTER USER \"db_user\" WITH PASSWORD 'db_user'"
          PGPASSWORD=postgres createdb   --echo -U postgres -h "${DB_SERVICE_URL}" -p "${DB_SERVICE_PORT}" --owner=db_user my_db
        image: postgres:latest
        name: postgres-on-k8s-job-to-set-up-db
        resources: {}
      restartPolicy: Never
status: {}
