apiVersion: batch/v1beta1
kind: CronJob
metadata:
  creationTimestamp: null
  name: postgres-on-k8s-cronjob-insert-db
spec:
  jobTemplate:
    metadata:
      creationTimestamp: null
      name: postgres-on-k8s-cronjob-insert-db
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - command:
            - /bin/bash
            - -c
            - |-
              IFS=$'\n\t'
              set -euxo pipefail

              for _ in {1..60}
              do
                PGPASSWORD="$CLIENT_PASSWORD" psql \
                  --user="$CLIENT_USER" \
                  --host="$DB_SERVICE_URL" \
                  --port="$DB_SERVICE_PORT" \
                  --dbname=my_db \
                  --command="
                    INSERT INTO some_table (description) VALUES (md5(random()::text))
                  "

                sleep 1
              done
            image: postgres:latest
            name: postgres-on-k8s-cronjob-insert-db
            resources: {}
          restartPolicy: OnFailure
  schedule: '* * * * *'
status: {}
