apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: postgres-on-k8s-job-to-set-up-db
spec:
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - |2-


          echo I worked
        image: postgres:latest
        name: postgres-on-k8s-job-to-set-up-db
        resources: {}
      restartPolicy: Never
status: {}
