apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: postgres-on-k8s-job-to-set-up-db
spec:
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - command:
        - /bin/bash
        - -c
        - |-
          IFS=$'\n\t'
          set -euxo pipefail

          PGPASSWORD="$POSTGRES_PASSWORD" createuser --echo \
            --username="$POSTGRES_USER" \
            --host="$DB_SERVICE_URL" \
            --port="$DB_SERVICE_PORT" \
            db_user

          PGPASSWORD="$POSTGRES_PASSWORD" psql \
            --username="$POSTGRES_USER" \
            --host="$DB_SERVICE_URL" \
            --port="$DB_SERVICE_PORT" \
            --command="
              ALTER USER \"db_user\" WITH PASSWORD 'db_user'
            "

          PGPASSWORD="$POSTGRES_PASSWORD" createdb --echo \
            --username="$POSTGRES_USER" \
            --host="$DB_SERVICE_URL" \
            --port="$DB_SERVICE_PORT" \
            --owner=db_user \
            my_db

          PGPASSWORD=db_user psql \
            --username=db_user \
            --host="$DB_SERVICE_URL" \
            --port="$DB_SERVICE_PORT" \
            --dbname=my_db \
            --command="
              CREATE TABLE some_table (
                id            SERIAL PRIMARY KEY,
                description   TEXT
              )
            "
        image: postgres:latest
        name: postgres-on-k8s-job-to-set-up-db
        resources: {}
      restartPolicy: Never
status: {}
