apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-on-k8s
  name: nginx-on-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-on-k8s
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-on-k8s
    spec:
      containers:
      - image: nginx:stable
        name: nginx
        ports:
        - containerPort: 80
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginx-on-k8s
  name: nginx-on-k8s
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-on-k8s
  type: ClusterIP
status:
  loadBalancer: {}
