apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-on-k8s
  name: nginx-on-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-on-k8s
  strategy: {}
  template:
    metadata:
      labels:
        app: nginx-on-k8s
    spec:
      containers:
      - image: nginx:stable
        name: nginx
        ports:
        - containerPort: 80
        resources: {}
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: html-files
      volumes:
      - name: html-files
        persistentVolumeClaim:
          claimName: shared-data-persistent-volume-claim
status: {}
