apiVersion: v1
kind: Service
metadata:
  annotations:
    creator: Marek Dudek
  creationTimestamp: null
  labels:
    app: web-server-clusterip
    owner: mdudek
    variant: development
  name: dev-web-server-clusterip
  namespace: dev
spec:
  ports:
  - name: 7071-80
    port: 7071
    protocol: TCP
    targetPort: 80
  selector:
    app: web-server-clusterip
    owner: mdudek
    variant: development
  type: ClusterIP
status:
  loadBalancer: {}
