apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/deployment.yaml
  - ../../base/service-nodeport.yaml

images:
  - name: nginx
    newTag: latest

commonAnnotations:
  creator: Marek Dudek

commonLabels:
  variant: with-nodeport-service
  owner: mdudek

nameSuffix: -np