apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/deployment.yaml
  - ../../base/service-nodeport.yaml

nameSuffix: -np

commonLabels:
  variant: with-nodeport-service