apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginx
  name: nginx
spec:
  ports:
  - name: 7072-8082
    port: 7072
    protocol: TCP
    targetPort: 8082
  selector:
    app: nginx
  type: NodePort
status:
  loadBalancer: {}
