apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: rest-server
  name: rest-server
spec:
  ports:
  - name: 7072-8082
    port: 7072
    protocol: TCP
    targetPort: 8082
  selector:
    app: rest-server
  type: NodePort
status:
  loadBalancer: {}
