apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: rest-server
  name: rest-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest-server
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rest-server
    spec:
      containers:
      - image: marekdudek/rest-server
        name: rest-server
        ports:
        - containerPort: 8082
        - containerPort: 5005
        resources: {}
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8082
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8082
        lifecycle:
          preStop:
            exec:
              command: ["sh", "-c", "sleep 10"]
        env:
          - name: JAVA_TOOL_OPTIONS
            value: -agentlib:jdwp=transport=dt_socket,address=5005,server=y,suspend=n
          - name: SPRING_PROFILES_ACTIVE
            value: postgres-kubernetes
status: {}
