apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web-client
    variant: with-nodeport-client
  name: web-client-np
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-client
      variant: with-nodeport-client
  strategy: {}
  template:
    metadata:
      labels:
        app: web-client
        variant: with-nodeport-client
    spec:
      containers:
      - command:
        - /usr/local/bin/bash
        - -c
        - |-
          IFS=$'\n\t'
          set -euxo pipefail

          while true;
          do
            date
            wget --quiet --spider "$WEB_SERVER":"$PORT" || exit
            sleep 1
          done
        env:
        - name: WEB_SERVER
          value: web-server-np
        - name: PORT
          value: "7072"
        image: bash
        name: bash
        resources: {}
status: {}
