apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/nginx-on-k8s-deployment.yaml
  - ../../base/nginx-on-k8s-service-clusterip.yaml

patchesStrategicMerge:
- shared-data.yaml
