apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-on-k8s
spec:
  template:
    spec:
      containers:
        - name: nginx
          volumeMounts:
            - name: html-files
              mountPath: /usr/share/nginx/html
      volumes:
        - name: html-files
          persistentVolumeClaim:
            claimName: shared-data-persistent-volume-claim