apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: web-server
    variant: with-clusterip-service
  name: web-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-server
      variant: with-clusterip-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: web-server
        variant: with-clusterip-service
    spec:
      containers:
      - image: nginx:latest
        name: nginx
        ports:
        - containerPort: 80
        resources: {}
status: {}
