apiVersion: batch/v1
kind: Job
metadata:
  labels:
    variant: empty-dir-volume
  name: postgres-on-k8s-job-to-tear-down-db-ed
spec:
  template:
    metadata:
      labels:
        variant: empty-dir-volume
    spec:
      containers:
      - command:
        - /bin/bash
        - -c
        - |-
          IFS=$'\n\t'
          set -euxo pipefail

          PGPASSWORD="$POSTGRES_PASSWORD" dropdb --echo \
            --username="$POSTGRES_USER" \
            --host="$DB_SERVICE_URL" \
            --port="$DB_SERVICE_PORT" \
            my_db

          PGPASSWORD="$POSTGRES_PASSWORD" dropuser --echo \
            --username="$POSTGRES_USER" \
            --host="$DB_SERVICE_URL" \
            --port="$DB_SERVICE_PORT" \
            db_user
        env:
        - name: DB_SERVICE_URL
          value: postgres-on-k8s-ed
        - name: DB_SERVICE_PORT
          value: "5432"
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: pg-db-admin-credentials-alt
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: pg-db-admin-credentials-alt
        image: postgres:latest
        name: postgres-on-k8s-job-to-tear-down-db
        resources: {}
      restartPolicy: Never
status: {}
