apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    variant: empty-dir-volume
  name: postgres-on-k8s-cronjob-copy-to-nginx-ed
spec:
  jobTemplate:
    metadata:
      labels:
        variant: empty-dir-volume
      name: postgres-on-k8s-cronjob-copy-to-nginx
    spec:
      template:
        metadata:
          labels:
            variant: empty-dir-volume
        spec:
          containers:
          - command:
            - /bin/bash
            - -c
            - |-
              IFS=$'\n\t'
              set -euxo pipefail

              PGPASSWORD="$CLIENT_PASSWORD" psql \
                --user="$CLIENT_USER" \
                --host="$DB_SERVICE_URL" \
                --port="$DB_SERVICE_PORT" \
                --dbname=my_db \
                --output=index.html \
                --html \
                --command="
                  SELECT * FROM some_table
                "

              cp index.html /usr/share/nginx/html
            env:
            - name: DB_SERVICE_URL
              value: postgres-on-k8s-ed
            - name: DB_SERVICE_PORT
              value: "5432"
            - name: CLIENT_USER
              valueFrom:
                secretKeyRef:
                  key: username
                  name: pg-db-client-credentials-alt
            - name: CLIENT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: pg-db-client-credentials-alt
            image: postgres:latest
            name: postgres-on-k8s-cronjob-copy-to-nginx
            resources: {}
            volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: html-files
          restartPolicy: OnFailure
          volumes:
          - name: html-files
            persistentVolumeClaim:
              claimName: shared-data-persistent-volume-claim
  schedule: '* * * * *'
status: {}
