apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: postgres-on-k8s
    variant: empty-dir-volume
  name: postgres-on-k8s-ed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-on-k8s
      variant: empty-dir-volume
  strategy: {}
  template:
    metadata:
      labels:
        app: postgres-on-k8s
        variant: empty-dir-volume
    spec:
      containers:
      - env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: pg-db-admin-credentials-alt
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: pg-db-admin-credentials-alt
        image: postgres:latest
        name: postgres
        ports:
        - containerPort: 5432
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-data
      volumes:
      - emptyDir: {}
        name: postgres-data
status: {}
