apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    variant: empty-dir-volume
  name: postgres-on-k8s-cronjob-insert-db-ed
spec:
  jobTemplate:
    metadata:
      labels:
        variant: empty-dir-volume
      name: postgres-on-k8s-cronjob-insert-db
    spec:
      template:
        metadata:
          labels:
            variant: empty-dir-volume
        spec:
          containers:
          - command:
            - /bin/bash
            - -c
            - |-
              IFS=$'\n\t'
              set -euxo pipefail

              for _ in {1..60}
              do
                PGPASSWORD="$CLIENT_PASSWORD" psql \
                  --user="$CLIENT_USER" \
                  --host="$DB_SERVICE_URL" \
                  --port="$DB_SERVICE_PORT" \
                  --dbname=my_db \
                  --command="
                    INSERT INTO some_table (description) VALUES (md5(random()::text))
                  "

                sleep 1
              done
            env:
            - name: DB_SERVICE_URL
              value: postgres-on-k8s-ed
            - name: DB_SERVICE_PORT
              value: "5432"
            - name: CLIENT_USER
              valueFrom:
                secretKeyRef:
                  key: username
                  name: pg-db-client-credentials-alt
            - name: CLIENT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: pg-db-client-credentials-alt
            image: postgres:latest
            name: postgres-on-k8s-cronjob-insert-db
            resources: {}
          restartPolicy: OnFailure
  schedule: '* * * * *'
status: {}
