apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: postgres-on-k8s
    variant: disposable-database
  name: postgres-on-k8s-dd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-on-k8s
      variant: disposable-database
  strategy: {}
  template:
    metadata:
      labels:
        app: postgres-on-k8s
        variant: disposable-database
    spec:
      containers:
      - env:
        - name: POSTGRES_PASSWORD
          value: postgres
        image: postgres:latest
        name: postgres
        ports:
        - containerPort: 5432
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: postgres-on-k8s
    variant: disposable-database
  name: postgres-on-k8s-dd
spec:
  ports:
  - name: "5432"
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: postgres-on-k8s
    variant: disposable-database
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  labels:
    variant: disposable-database
  name: postgres-on-k8s-job-to-set-up-db-dd
spec:
  template:
    metadata:
      creationTimestamp: null
      labels:
        variant: disposable-database
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - |-
          PGPASSWORD=postgres createuser --echo -U postgres -h postgres-on-k8s-dd db_user
          PGPASSWORD=postgres psql              -U postgres -h postgres-on-k8s-dd -c "ALTER USER \"db_user\" WITH PASSWORD 'db_user'"
          PGPASSWORD=postgres createdb   --echo -U postgres -h postgres-on-k8s-dd --owner=db_user my_db
        image: postgres:latest
        name: postgres-on-k8s-job-to-set-up-db
        resources: {}
      restartPolicy: Never
status: {}
---
apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  labels:
    variant: disposable-database
  name: postgres-on-k8s-job-to-tear-down-db-dd
spec:
  template:
    metadata:
      creationTimestamp: null
      labels:
        variant: disposable-database
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - |-
          PGPASSWORD=postgres dropdb   --echo -U postgres -h postgres-on-k8s-dd my_db
          PGPASSWORD=postgres dropuser --echo -U postgres -h postgres-on-k8s-dd db_user
        image: postgres:latest
        name: postgres-on-k8s-job-to-tear-down-db
        resources: {}
      restartPolicy: Never
status: {}
