apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: postgres-on-k8s
    variant: disposable-database
  name: postgres-on-k8s
spec:
  ports:
  - name: "5432"
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: postgres-on-k8s
    variant: disposable-database
  type: ClusterIP
status:
  loadBalancer: {}
