apiVersion: batch/v1
kind: Job
metadata:
  labels:
    variant: disposable-database
  name: postgres-on-k8s-job-to-set-up-db-dd
spec:
  template:
    metadata:
      labels:
        variant: disposable-database
    spec:
      containers:
      - command:
        - /bin/bash
        - -c
        - |-
          IFS=$'\n\t'
          set -euxo pipefail

          PGPASSWORD="$POSTGRES_PASSWORD" createuser --echo \
            --username="$POSTGRES_USER" \
            --host="$DB_SERVICE_URL" \
            --port="$DB_SERVICE_PORT" \
            "$CLIENT_USER"

          PGPASSWORD="$POSTGRES_PASSWORD" psql \
            --username="$POSTGRES_USER" \
            --host="$DB_SERVICE_URL" \
            --port="$DB_SERVICE_PORT" \
            --command="
              ALTER USER \"$CLIENT_USER\" WITH PASSWORD '$CLIENT_PASSWORD'
            "

          PGPASSWORD="$POSTGRES_PASSWORD" createdb --echo \
            --username="$POSTGRES_USER" \
            --host="$DB_SERVICE_URL" \
            --port="$DB_SERVICE_PORT" \
            --owner="$CLIENT_USER" \
            my_db

          PGPASSWORD="$CLIENT_PASSWORD" psql \
            --username="$CLIENT_USER" \
            --host="$DB_SERVICE_URL" \
            --port="$DB_SERVICE_PORT" \
            --dbname=my_db \
            --command="
              CREATE TABLE some_table (
                id            SERIAL PRIMARY KEY,
                description   TEXT
              )
            "
        env:
        - name: DB_SERVICE_URL
          value: postgres-on-k8s-dd
        - name: DB_SERVICE_PORT
          value: "5432"
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: pg-db-admin-credentials
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: pg-db-admin-credentials
        - name: CLIENT_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: pg-db-client-credentials
        - name: CLIENT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: pg-db-client-credentials
        image: postgres:latest
        name: postgres-on-k8s-job-to-set-up-db
        resources: {}
      restartPolicy: Never
status: {}
