apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: postgres-on-k8s
    variant: disposable-database
  name: postgres-on-k8s-dd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-on-k8s
      variant: disposable-database
  strategy: {}
  template:
    metadata:
      labels:
        app: postgres-on-k8s
        variant: disposable-database
    spec:
      containers:
      - env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: pg-db-admin-credentials
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: pg-db-admin-credentials
        image: postgres:latest
        name: postgres
        ports:
        - containerPort: 5432
        resources: {}
status: {}
