apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: date-every-sec
  name: date-every-sec
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - while true; do date; sleep 1; done
    image: busybox
    name: date-every-sec
    ports:
    - containerPort: 8080
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
