apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: dpl-1
  name: dpl-1
  namespace: test 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dpl-1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: dpl-1
    spec:
      containers:
      - image: k8s.gcr.io/echoserver:1.4
        name: echoserver
        resources: {}
status: {}
