apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: echoserver-one
  name: echoserver-nodeport-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: echoserver-one
  type: NodePort
status:
  loadBalancer: {}
