apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: echoserver-three
  name: echoserver-three
spec:
  containers:
  - image: k8s.gcr.io/echoserver:1.4
    name: echoserver-three
    ports:
    - containerPort: 8080
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
