apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: echoserver-nodeport
  name: service-1
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: echoserver-nodeport
  type: NodePort
status:
  loadBalancer: {}
