apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: echoserver-loadbalancer
  name: service-2
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: echoserver-loadbalancer
  type: LoadBalancer
status:
  loadBalancer: {}
