apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: echoserver-two
  name: echoserver-loadbalancer-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: echoserver-two
  type: LoadBalancer
status:
  loadBalancer: {}
