apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: dpl-2
  name: svc-2
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: dpl-2
  type: LoadBalancer
status:
  loadBalancer: {}
