apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-dir-pv
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/my-data/