apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-dir-pvc
spec:
  volumeName: data-dir-pv
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi