kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-persistent-volume
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"