apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    creator: Marek Dudek
  creationTimestamp: null
  labels:
    app: web-client
    owner: mdudek
    variant: production
  name: web-client
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-client
      owner: mdudek
      variant: production
  strategy: {}
  template:
    metadata:
      annotations:
        creator: Marek Dudek
      creationTimestamp: null
      labels:
        app: web-client
        owner: mdudek
        variant: production
    spec:
      containers:
      - command:
        - /usr/local/bin/bash
        - -c
        - |-
          IFS=$'\n\t'
          set -euxo pipefail

          while true;
          do
            date
            wget --quiet --spider "$WEB_SERVER":"$PORT" || exit
            sleep 1
          done
        image: bash
        name: bash
        resources: {}
status: {}
