apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: multi
  name: multi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multi
  strategy: {}
  template:
    metadata:
      labels:
        app: multi
    spec:
      containers:
      - command:
        - /usr/local/bin/bash
        - -c
        - |-
          IFS=$'\n\t'
          set -euxo pipefail

          while true;
          do
            echo I read
            sleep 1
          done
        image: bash
        name: reader
        resources: {}
      - command:
        - /usr/local/bin/bash
        - -c
        - |-
          IFS=$'\n\t'
          set -euxo pipefail

          mkdir /mnt/files

          COUNTER=0

          while true;
          do
            touch /mnt/files/file-$COUNTER.txt
            sleep 1
            (( COUNTER++ )) || true
          done
        image: bash
        name: writer
        resources: {}
      - image: nginx:stable
        name: nginx
        ports:
        - containerPort: 80
        resources: {}
      volumes:
      - emptyDir: {}
        name: shared-data
status: {}
