apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: multi
  name: multi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multi
  strategy: {}
  template:
    metadata:
      labels:
        app: multi
    spec:
      containers:
      - command:
        - /usr/local/bin/bash
        - -c
        - |2

          while true;
          do
            echo I read
            sleep 1
          done
        image: bash
        name: reader
        resources: {}
      - command:
        - /usr/local/bin/bash
        - -c
        - |2

          while true;
          do
            echo I write
            sleep 1
          done
        image: bash
        name: writer
        resources: {}
      - image: nginx:stable
        name: nginx
        ports:
        - containerPort: 80
        resources: {}
status: {}
