apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-on-k8s
spec:
  template:
    spec:
      volumes:
        - name: postgres-data
          emptyDir: {}
      containers:
        - name: postgres
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
          env:
            - name: POSTGRES_PASSWORD
              value: minikube