apiVersion: batch/v1
kind: Job
metadata:
  name: postgres-on-k8s-job-to-set-up-db
spec:
  template:
    spec:
      containers:
        - name: postgres-on-k8s-job-to-set-up-db
          env:
          - name: DB_SERVICE_URL
            value: postgres-on-k8s-ed
          - name: DB_SERVICE_PORT
            value: "5432"
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                key: username
                name: pg-db-admin-credentials-alt
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: pg-db-admin-credentials-alt