apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/deployment.yaml
  - ../../base/service-loadbalancer.yaml

nameSuffix: -lb

commonLabels:
  variant: with-loadbalancer-service