apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/deployment.yaml

nameSuffix: -np

commonLabels:
  variant: with-nodeport-client

patchesStrategicMerge:
  - env-variables-patch.yaml